name: Build EXE

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller tkcalendar

      - name: Clean up previous builds
        run: |
          echo "Cleaning up previous builds..."
          rm -rf dist/ build/  # Xóa thư mục dist và build

      - name: Build EXE
        run: pyinstaller main.spec  # Sử dụng main.spec để build

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v2
        with:
          name: QuanLyKhachHang
          path: dist/main.exe  # Đảm bảo đường dẫn chính xác
