name: Build EXE

on:
  push:
    branches: [main]  # Chạy khi có commit lên nhánh main

jobs:
  build:
    runs-on: windows-latest  # Chạy trên môi trường Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Lấy mã nguồn từ repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Thiết lập phiên bản Python cần thiết

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Cập nhật pip
          pip install pyinstaller tkcalendar  # Cài đặt PyInstaller và tkcalendar

      - name: Build EXE
        run: pyinstaller main.spec  # Build từ file spec, đảm bảo bạn có file main.spec

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: QuanLyKhachHang  # Tên artifact khi tải lên
          path: dist/main.exe  # Đảm bảo đường dẫn và tên file .exe chính xác sau khi build
