name: Build EXE

on:
  push:
    branches: [main]

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller tkcalendar

      - name: Build EXE
        run: pyinstaller main.spec

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: QuanLyKhachHang
          path: dist/main.exe
