name: Build EXE

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clear cache
        run: |
          # Thêm lệnh xóa cache ở đây nếu bạn sử dụng cache để giảm thiểu thời gian build.
          # Bạn có thể thêm hoặc sửa lại để làm mới cache của các bước trước khi cài đặt lại thư viện.
          rm -rf ~/.cache/pip  # Xóa cache pip
          rm -rf ~/.cache/pyinstaller  # Nếu bạn dùng PyInstaller và muốn xóa cache build cũ

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller tkcalendar

      - name: Build EXE
        run: pyinstaller main.spec

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-exe
          path: dist/main.exe
